#!/usr/bin/env python3
# Transcode the Adafruit GFX 5x7 glcdfont into a Zephyr CFB font (font0608, 6x8, MONO_VPACKED).
# CFB VPACKED (cfb.c get_glyph_byte): column-major, 1 byte/col for 8px height, LSB=top pixel.
# glcdfont is column-major, 5 bytes/char, LSB=top -> a direct transcode (pad a 6th spacing col).
import re, sys

src = open('glcdfont.c').read()
bytes_ = [int(x, 16) for x in re.findall(r'0[xX][0-9a-fA-F]{2}', src)]
assert len(bytes_) >= 1280, f"expected >=1280 font bytes, got {len(bytes_)}"

FIRST, LAST = 32, 126
glyphs = []
for c in range(FIRST, LAST + 1):
    cols = bytes_[c*5 : c*5 + 5]
    glyphs.append(cols + [0x00])          # 5 data columns + 1 spacing column = width 6

# ---- self-verify: render a few glyphs EXACTLY as CFB reads them (col-major, LSB=top) ----
def show(ch):
    g = glyphs[ord(ch) - FIRST]
    print(f"  '{ch}':")
    for row in range(8):
        line = ''.join('#' if (g[col] >> row) & 1 else '.' for col in range(6))
        print('    ' + line)
for ch in "AMgy5#":
    show(ch)

# ---- emit the CFB font .c ----
out = []
out.append('/* GENERATED by variants/xiao_nrf54l15/tools/gen_cfb_font.py — do not edit by hand.')
out.append(' * Source: Adafruit-GFX-Library glcdfont.c (classic 5x7, BSD). A 6x8 MONO_VPACKED CFB')
out.append(' * font (5 data columns + 1 spacing) so the ui-tiny UITask renders at its designed size. */')
out.append('#include <zephyr/display/cfb.h>\n')
out.append(f'static const uint8_t cfb_font_0608[{LAST-FIRST+1}][6] = {{')
for i, g in enumerate(glyphs):
    out.append('\t{' + ', '.join(f'0x{b:02x}' for b in g) + f'}},  /* {chr(FIRST+i)!r} */')
out.append('};\n')
out.append(f'FONT_ENTRY_DEFINE(font0608, 6, 8, CFB_FONT_MONO_VPACKED, cfb_font_0608, {FIRST}, {LAST});')
open('cfb_font_0608.c', 'w').write('\n'.join(out) + '\n')
print(f"\nwrote cfb_font_0608.c  ({LAST-FIRST+1} glyphs)")
